server:
  port: 8123
  servlet:
    context-path: /api

fanta:
  client:
    access-key: fanta
    secret-key: asdqwe

dubbo:
  application:
    name: dubbo-spring-boot-consumer
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: -1